### ISSUE TITLE
TO-DO's and Ideas for Release

### ISSUE THREAD

**Issue by Standecco** [Standecco/ROKerbalism#1]
First Release
- [x] Add processes and configs for the Shuttle and the Orion capsule
- [x] Support CxAerospace and other space station parts
- [x] Configure Soviet capsules
- [x] Adjust Shielding: it's currently using lead while it should use aluminum or polyethylene 
- [x] Tweak stress values to allow historical missions and nerf interplanetary fly-by's in a mercury capsule
- [x] ~~Add historically correct/plausible memory storage to all parts~~ disabled for the initial release
- [x] Add RP-1 support and experiment cfgs with the 3.0 science system
- [x] Fix pressurized status so that stress goes up faster in Mercury and other capsules that require a suit

1.0
- [x] Port at least the first tiers of all the existing experiments to the new system
- [x] Add configure modules for probes
- [x] Balance values (needs a pre-release and playtesting)
- [x] Determine correct data rate and EC consumption for all experiments (needs playtesting)
- [x] Create crew experiments
- [x] Add more crew experiments for mature and advanced capsules
- [x] Add support to RTGs and radiation emission to NERVAs

Next Releases
- [ ] Integrate RP-1 procedural avionics with hard disks
- [x] Add Solar Weather
- [ ] Finish adding volume and surface values for all parts
- [x] Completely remake the RSS radiation profile
- [ ] Add near future life support systems to allow long term mars missions
- [ ] RealISRU support (might be incompatible, untested)

Ideas
- Upgrades for EVA suits? Apollo doubled EVA duration from Apollo 14 and Shuttle/ISS suits improved duration again; Mars suits would have Orion-like vacuum scrubbers and again, improved duration (currently not possible)
- Simulate different systems for memory storage (mainly magnetic) by adding upgradable hard drives to the experiment part, and then moving to proper hard disks inside probe cores

**Comment by ockidj** [comment]
Procedural hard drives could come in the from of service modules. It could be a fuel in real fuels with different tiers.
Or maybe use the science storage part from stock and just add configurations.
